### ISSUE TITLE
Add a development mode where templates are always reloaded from disk

### ISSUE THREAD

**Issue by gsingh93** [sunng87/handlebars-iron#15]
If I make a change in a template, I currently have to restart the server to see the change appear. It would be nice if there was some development mode that always loaded the latest version of the template from disk, so I wouldn't have to rerun my binary every time I make a template change.

**Comment by sunng87** [comment]
Have you tried Live reload mode?
https://github.com/sunng87/handlebars-iron#live-reload

**Comment by gsingh93** [comment]
Oh, that's exactly what I wanted. Sorry about the noise.
