### ISSUE TITLE
rustup to handlebars-rust 0.12

### ISSUE THREAD

**Issue by untitaker** [sunng87/handlebars-iron#22]
Unfortunately https://github.com/sunng87/handlebars-rust/commit/8a4a575bb45044f8462a7a120b9f189b016ec43e makes this very hard, see comment there.

**Comment by sunng87** [comment]
Thanks for pointing out. I've noticed this issue when I about to release 0.10 and failed to compile it with handlebars 0.12.0. I will fix it soon.
