### ISSUE TITLE
update serde to 0.7

### ISSUE THREAD

**Issue by euclio** [sunng87/handlebars-iron#32]
I see that [sunng87/handlebars-rust](http://github.com/sunng87/handlebars-rust) has already been updated.

**Comment by sunng87** [comment]
I just update in the repo but still haven't release neither of this and handlbars to crates.io
Please use git version for now. Thanks!

**Comment by sunng87** [comment]
hmm... seems something is broken with serde 0.7.0

**Comment by sunng87** [comment]
Because iron still depends serde 0.6.x, we cannot update 0.7.0 atm

**Comment by sunng87** [comment]
Fixed in 77b36a7
