### ISSUE TITLE
DirectorySource not loading templates in a heirarchy

### ISSUE THREAD

**Issue by ghotiphud** [sunng87/handlebars-iron#36]
Loading templates puts them all in a flat namespace instead of a heirarchy like described here in the README.

For DirectorySource, handlebars engine will walk the directory specified by prefix, try to register all templates matches the suffix, and extract its name as template name. For instance, ./examples/templates/some/path/index.hbs will be registered as some/path/index.

**Comment by sunng87** [comment]
Thank you for reporting. I confirm this is a bug. I will look into it asap.

**Comment by sunng87** [comment]
Fixed in cd9c33c and will be released in 0.13.2
