### ISSUE TITLE
Handle templates set on IronErrors

### ISSUE THREAD

**Issue by untitaker** [sunng87/handlebars-iron#39]
Currently, modifying the response of an `Err(IronError)` to have a template is not processed by the `AfterMiddleware` in this package, and the response body stays empty.

To process errors as well, `catch` needs to implemented besides `after`.

**Comment by sunng87** [comment]
This makes sense. I will add support for `catch` very soon.

**Comment by sunng87** [comment]
Fixed in #40

**Comment by sunng87** [comment]
released in 0.15.0

**Comment by untitaker** [comment]
Excellent, thank you!
