### ISSUE TITLE
Glob matching fails silently on non-existing dir

### ISSUE THREAD

**Issue by golddranks** [sunng87/handlebars-iron#4]
When setting a non-existing directory for the prefix, I think it would be desirable that glob matching would panic and report the error. I just noticed that it fails silently, since I ran `cargo run` inside `src/` whereas I usually run it from the cargo root dir.

I also thought that it would be maybe nice to change glob to std::fs::WalkDir iterator to eliminate a dependency, but that is marked as unstable, and I don't know whether it'll stabilise until the 1.0 beta. But what do you think about using it when it stabilises?

**Comment by sunng87** [comment]
Thanks for reporting! I will definitely add a check for prefix directory.

`std::fs::WalkDir` should be better than glob in our use case. It's beta but I think it's OK to use it our library. Pull request for this is welcomed.

**Comment by sunng87** [comment]
fs_walk now in master.
