### ISSUE TITLE
[Suggestion] Implementing Handler for Templates

### ISSUE THREAD

**Issue by AtheMathmo** [sunng87/handlebars-iron#49]
Hey!

This library is awesome - thank you for your continued work on it.

I'm making this issue to ask if you think it is worth implementing `Handler` for `Template`? Currently I am doing something like this in my code:

``` rust
pub struct TemplateHandler {
    path: &'static str
}

impl TemplateHandler {
    pub fn new(path: &'static str) -> TemplateHandler {
        TemplateHandler { path: path }
    }
}

impl Handler for TemplateHandler {
    fn handle(&self, _: &mut Request) -> IronResult<Response> {
        let mut resp = Response::new();
        resp.set_mut(Template::new(self.path, ())).set_mut(status::Ok);
        Ok(resp)
    }
}

// Mount the templating
mount.mount("/",
            router!(
    get "/" => TemplateHandler::new("index"),
    get "/kmeans" => TemplateHandler::new("kmeans"),
    get "/dbscan" => TemplateHandler::new("dbscan"),
));
```

Maybe I'm missing the point but I think it would be nice to provide this behavior within this library. I know there are many use cases that will not simply be rendering a web page without providing new content. But I think this is common enough that it is valuable.

An alternative could be to implement `Handler` for a new wrapper type as I have - perhaps called `RenderTemplate`?

In any case, it is not too much extra code to add on and the library is very useful as is!

**Comment by sunng87** [comment]
If I understand correctly, you were using template as static pages?

I think that's a good idea. And if we can pass some default data into the page, for example, parameters, query strings, it would be stronger:

``` rust
impl Handler for TemplateHandler {
    fn handle(&self, req: &mut Request) -> IronResult<Response> {
        let mut resp = Response::new();
        resp.set_mut(Template::new(self.path, parse_data_from_request(req))).set_mut(status::Ok);
        Ok(resp)
    }
}
```

WDYT?

**Comment by AtheMathmo** [comment]
Yes you're right - I am using templates as static pages (to keep the client side views tidy).

That is a good idea! Could we have the `parse_data_from_request` function be defined by the `TemplateHandler`? I'm not sure I have the knowledge to describe how that function should look.

**Comment by sunng87** [comment]
Yes, the `parse_data_from_request` is a built-in function that extracts some data from `Request`.

**Comment by AtheMathmo** [comment]
But this is a function that we would define within this library?

I meant to ask whether it would be sensible to let the user define this function (`parse_data_from_request`) within the handler. I mean something like:

**(Edit: Working version in edit at end.)**

``` rust
pub struct TemplateHandler<F, U : ToJson>
    where F: FnOnce(Request) -> U {
    path: &'static str,
    get_data: Box<T>,
}
```

And we could provide something like:

``` rust
impl<F: FnOnce(Request) -> ()> TemplateHandler<F, ()> {
    pub fn new_static(path: &'static str) -> TemplateHandler<F, ()> {
        TemplateHandler {
            path: path,
            get_data: Box::new(|_| { () }),
        }
    }
}
```

Note that [this doesn't actually compile](https://play.rust-lang.org/?gist=b4b7e6a8ed8a78e92b0f3470e3b5cb46&version=stable&backtrace=0) - I'm sure there should be a way though...

---

**Working version:**

``` rust
pub struct TemplateHandler<U : ToJson> {
    path: &'static str,
    get_data: Box<Fn(Request) -> U>,
}

impl TemplateHandler<()> {
    pub fn new_static(path: &'static str) -> TemplateHandler<()> {
        TemplateHandler {
            path: path,
            get_data: Box::new(|_| ()),
        }
    }
}
```

We could also provide some other defaults while allowing the user to construct their own.

Maybe this all just too complex though, let me know what you think :)

**Comment by sunng87** [comment]
I think this is a little complex and it's getting similar to a normal iron handler.

My idea is to provide a standard `get_data` function to extract information from request and pass them to the template. But now I'm afraid this approach will lead handlebars template to early days of JSP and PHP. Users might tend to write their business logic into the template, which is a bad idea.

**Comment by AtheMathmo** [comment]
I can't comment on the JSP/PHP - I'm not much of a web developer - but I agree that it does look too complex.

What would the `get_data` function you're proposing look like? Perhaps it would still be a worthy addition to simply add a static template handler with the functionality of `new_static` above?

**Comment by sunng87** [comment]
My idea is to make a map of all request parameters as template context. The parameters can be extracted by [params](https://github.com/iron/params) using:

``` rust
fn get_data(req: &Request) -> Map {
     req.get_ref::<Params>().unwrap();
}
```

If this works for you, I will make it a separated module because it introduces [params](https://github.com/iron/params), and encourages logic in template (which is not welcomed by some people)

**Comment by AtheMathmo** [comment]
That sounds good to me!

**Comment by sunng87** [comment]
The lib is here:

https://github.com/sunng87/handlebars-template-handler

**Comment by AtheMathmo** [comment]
Nice work! Thank you. Feel free to close.
