### ISSUE TITLE
Porting to serde 1.0

### ISSUE THREAD

**Issue by winding-lines** [sunng87/handlebars-iron#59]
@sunng87 are you already working on porting this library to serde 1.0 and corresponding handlebars-rust?

**Comment by sunng87** [comment]
Yes, I'm almost done with that.

**Comment by winding-lines** [comment]
If it's of any help the following seems to work for me:

https://github.com/winding-lines/handlebars-iron/commit/ba9bfd42a721df57b5f72bb3ceddb0458eb0c3af

**Comment by sunng87** [comment]
Thank you! Could you please open a pull request for that?

**Comment by winding-lines** [comment]
Opened :)

**Comment by sunng87** [comment]
Implemented in #60
