### ISSUE TITLE
Where to put CSS/JS files?

### ISSUE THREAD

**Issue by gsingh93** [sunng87/handlebars-iron#6]
I have a template called `index.hbs` in my `templates` folder and now I'm trying to include some CSS and JS files in the HTML. However, no matter where I put my CSS/JS folder, the server can never find these files. Where am I supposed to put them for them to get picked up?

**Comment by sunng87** [comment]
You might want to checkout the [static middleware](https://github.com/iron/static) for iron. Put these resources files in a path, and mount the middleware configured for the path.

**Comment by gsingh93** [comment]
Thanks, I got it working.
