### ISSUE TITLE
Update to handlebars 1.0

### ISSUE THREAD

**Issue by est31** [sunng87/handlebars-iron#67]
Handlebars 1.0 has been released. It would be great to update this crate to the new handlebars.

**Comment by sunng87** [comment]
Thanks! That was on my TODO. I'm just waiting upstream Iron's new release. The new maintainers has been active these days.

**Comment by sunng87** [comment]
Released in 0.27.0. Will include newer iron in next release.

**Comment by est31** [comment]
Thank you, @sunng87 !
